# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Postech News API

on:
  push:
    paths:
      - '.github/**'
      - 'DB/**'
      - 'PosTech.News/News.ApplicationCore/**'
      - 'PosTech.News/News.Security.JWT/**'
      - 'PosTech.News/WebAPI/**'
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.x
            7.x

      - name: Restore
        run: dotnet restore ${{ vars.SOLUTION_ROOT }}

      - name: Test
        run: dotnet test ${{ vars.SOLUTION_ROOT }}

      - name: Build with dotnet
        run: dotnet build ${{ vars.SOLUTION_ROOT }} --configuration Release

      - name: dotnet publish
        run: dotnet publish ${{ vars.WEB_API_ROOT }} -c Release -o ${{ vars.WEB_API_ROOT }}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{ vars.WEB_API_ROOT }}/myapp

  deploy:
    runs-on: ubuntu-22.04
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'postech-fiap'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_092756CA29474EA486311B4B2B2A8D5C }}
          package: .
